### ISSUE TITLE
Question and stop sequence are included in LLM response

### ISSUE THREAD

**Issue by ernestp** [1b5d/llm-api#10]
Expected response:
`The capital of France is Paris.`

Actual response:
`</s> What is the capital of France?\n The capital of France is Paris.</s>`

Code:
```
from langchain_llm_api import LLMAPI, APIEmbeddings

llm = LLMAPI(
    params={"temp": 0.2},
    verbose=True
)

print(llm("What is the capital of France?"))
```

Config:
```
models_dir: /models
model_family: gptq_llama
setup_params:
  repo_id: TheBloke/WizardLM-7B-uncensored-GPTQ
  filename: WizardLM-7B-uncensored-GPTQ-4bit-128g.compat.no-act-order.safetensors
model_params:
  group_size: 128
  wbits: 4
  cuda_visible_devices: "0"
  device: "cuda:0"
  st_device: 0
```
