### ISSUE TITLE
Is this quantized 7b ggml model too old?

### ISSUE THREAD

**Issue by Jawabiscuit** [1b5d/llm-api#2]
First, thanks for sharing your repo. I'm not understanding why I can't use this model directly. I may be missing something since I'm just learning. I was hoping to avoid having to download and mess around with llama-cpp to get this working. My goal is to spin up a web server to be able to generate and use embeddings with these models and use langchain at some point too.

![ubuntu_k3obZs11fa](https://user-images.githubusercontent.com/219464/231172038-139b342e-0098-4db7-985d-c0f49205366d.png)

My config.yaml

```
models_dir: /models
model_family: alpaca
model_name: 7b
setup_params:
  repo_id: Sosaka/Alpaca-native-4bit-ggml
  filename: ggml-alpaca-7b-q4.bin
  convert: true
  migrate: false
model_params:
  ctx_size: 2000
  seed: -1
  n_threads: 8
  n_batch: 2048
  n_parts: -1
  last_n_tokens_size: 16
```

What am I doing wrong? I tried setting `convert: true` thinking it would convert the old model, which I noticed [convert.py](https://github.com/1b5d/llm-api/blob/main/app/llms/llama/convert.py) but it doesn't seem to be used. I'm confused about which is better, convert.py or llama-cpp's [convert-unversioned-ggml-to-ggml.py](https://github.com/ggerganov/llama.cpp/blob/master/convert-unversioned-ggml-to-ggml.py) since the log says to use ggerganov's convert script. 

Guidance?
